import { auth } from "@/lib/auth";
import { redirect } from "next/navigation";
import { ManagePortalsClient } from "./portals-client";

export default async function ManagePortalsPage() {
  const session = await auth();

  if (!session || (session.user.role !== "ADMIN" && session.user.role !== "SUPER_ADMIN")) {
    redirect("/dashboard");
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-bold tracking-tight text-white mb-2">
          Manage Portals
        </h1>
        <p className="text-slate-400">
          Global view of all free portals generated by resellers.
        </p>
      </div>

      <ManagePortalsClient />
    </div>
  );
}
